// This is a Prisma schema file. Models will be generated by Prisma.
// For shared types, see @types/index.ts

// However, here are the base model definitions for reference:

/*
model User {
  id        String   @id @default(cuid())
  email     String   @unique
  password  String
  name      String
  role      String
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  leads     Lead[]
  deals     Deal[]
}

model Lead {
  id        String   @id @default(cuid())
  name      String
  email     String
  phone     String
  status    String
  value     Float?
  broker    Broker?  @relation(fields: [brokerId], references: [id])
  brokerId  String?
  property  Property? @relation(fields: [propertyId], references: [id])
  propertyId String?
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  deals     Deal[]
}

model Deal {
  id        String   @id @default(cuid())
  title     String
  status    String
  type      String
  value     Float
  lead      Lead     @relation(fields: [leadId], references: [id])
  leadId    String
  property  Property @relation(fields: [propertyId], references: [id])
  propertyId String
  broker    Broker   @relation(fields: [brokerId], references: [id])
  brokerId  String
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}

model Broker {
  id        String   @id @default(cuid())
  name      String
  email     String   @unique
  phone     String
  company   String?
  status    String
  pin       String?
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  leads     Lead[]
  deals     Deal[]
}

model Contact {
  id        String   @id @default(cuid())
  name      String
  email     String
  phone     String
  type      String
  status    String
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt
}

model Property {
  id        String   @id @default(cuid())
  address   String
  city      String
  province  String
  type      String
  price     Float
  area      Float
  createdAt DateTime @default(now())
  updatedAt DateTime @updatedAt

  leads     Lead[]
  deals     Deal[]
  auctions  Auction[]
}

model Auction {
  id          String   @id @default(cuid())
  property    Property @relation(fields: [propertyId], references: [id])
  propertyId  String
  startDate   DateTime
  endDate     DateTime
  minimumBid  Float
  status      String
  createdAt   DateTime @default(now())
  updatedAt   DateTime @updatedAt
}
*/

export const models = {
  User: 'User',
  Lead: 'Lead',
  Deal: 'Deal',
  Broker: 'Broker',
  Contact: 'Contact',
  Property: 'Property',
  Auction: 'Auction',
};
